# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faculty_research_info_mis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: listen

server:
  port: 9090

mybatis-plus:
  configuration:
    cache-enabled: false #禁用二级缓存
    local-cache-scope: statement #一级缓存指定为statement级别
